"""
config.py — all static constants: currencies, category colours, language strings, month map.
"""

CURRENCIES = {
    "EUR": {"name": "Euro",             "symbol": "€",   "rate_to_eur": 1.0},
    "USD": {"name": "US Dollar",        "symbol": "$",   "rate_to_eur": 1.08},
    "CAD": {"name": "Canadian Dollar",  "symbol": "CA$", "rate_to_eur": 1.47},
    "HUF": {"name": "Hungarian Forint", "symbol": "Ft",  "rate_to_eur": 394.0},
    "SEK": {"name": "Swedish Krona",    "symbol": "kr",  "rate_to_eur": 11.47},
    "TRY": {"name": "Turkish Lira",     "symbol": "₺",   "rate_to_eur": 35.26},
}
CURRENCY_CODES = list(CURRENCIES.keys())

# ── Category colours (semantic: same colour per category everywhere) ──────────
CATEGORY_COLORS = {
    "Restaurant":           "#e07b39",
    "Food":                 "#f0a500",
    "Grocery":              "#27ae60",
    "Transport":            "#3498db",
    "Hotel":                "#9b59b6",
    "Bar":                  "#c0392b",
    "Activity & Museums":   "#1abc9c",
    "Activités & Musées":   "#1abc9c",
    "Actividades & Museos": "#1abc9c",
    "Telephone":            "#7f8c8d",
    "Téléphone":            "#7f8c8d",
    "Teléfono":             "#7f8c8d",
    "Housing":              "#e74c3c",
    "Logement":             "#e74c3c",
    "Alojamiento":          "#e74c3c",
    "Entertainment":        "#e91e8c",
    "Loisirs":              "#e91e8c",
    "Ocio":                 "#e91e8c",
    "Health":               "#00bcd4",
    "Santé":                "#00bcd4",
    "Salud":                "#00bcd4",
    "Shopping":             "#ff9800",
    "Compras":              "#ff9800",
    "Nourriture":           "#f0a500",
    "Comida":               "#f0a500",
}
_DEFAULT_CAT_COLORS = [
    "#3498db", "#e07b39", "#27ae60", "#9b59b6", "#1abc9c",
    "#e74c3c", "#f39c12", "#00bcd4", "#e91e8c", "#7f8c8d", "#ff9800",
]


def cat_color(name: str, idx: int = 0) -> str:
    return CATEGORY_COLORS.get(name, _DEFAULT_CAT_COLORS[idx % len(_DEFAULT_CAT_COLORS)])


# ── Country name translations ─────────────────────────────────────────────────
COUNTRY_TRANSLATIONS = {
    "Austria":         {"EN": "Austria",         "FR": "Autriche",           "ES": "Austria"},
    "Belgium":         {"EN": "Belgium",          "FR": "Belgique",           "ES": "Bélgica"},
    "Bulgaria":        {"EN": "Bulgaria",         "FR": "Bulgarie",           "ES": "Bulgaria"},
    "Croatia":         {"EN": "Croatia",          "FR": "Croatie",            "ES": "Croacia"},
    "Czech Republic":  {"EN": "Czech Republic",   "FR": "République tchèque", "ES": "República Checa"},
    "Denmark":         {"EN": "Denmark",          "FR": "Danemark",           "ES": "Dinamarca"},
    "France":          {"EN": "France",           "FR": "France",             "ES": "Francia"},
    "Germany":         {"EN": "Germany",          "FR": "Allemagne",          "ES": "Alemania"},
    "Greece":          {"EN": "Greece",           "FR": "Grèce",              "ES": "Grecia"},
    "Hungary":         {"EN": "Hungary",          "FR": "Hongrie",            "ES": "Hungría"},
    "Ireland":         {"EN": "Ireland",          "FR": "Irlande",            "ES": "Irlanda"},
    "Italy":           {"EN": "Italy",            "FR": "Italie",             "ES": "Italia"},
    "Malta":           {"EN": "Malta",            "FR": "Malte",              "ES": "Malta"},
    "Netherlands":     {"EN": "Netherlands",      "FR": "Pays-Bas",           "ES": "Países Bajos"},
    "Norway":          {"EN": "Norway",           "FR": "Norvège",            "ES": "Noruega"},
    "Poland":          {"EN": "Poland",           "FR": "Pologne",            "ES": "Polonia"},
    "Portugal":        {"EN": "Portugal",         "FR": "Portugal",           "ES": "Portugal"},
    "Romania":         {"EN": "Romania",          "FR": "Roumanie",           "ES": "Rumanía"},
    "Slovakia":        {"EN": "Slovakia",         "FR": "Slovaquie",          "ES": "Eslovaquia"},
    "Spain":           {"EN": "Spain",            "FR": "Espagne",            "ES": "España"},
    "Sweden":          {"EN": "Sweden",           "FR": "Suède",              "ES": "Suecia"},
    "Switzerland":     {"EN": "Switzerland",      "FR": "Suisse",             "ES": "Suiza"},
    "Turkey":          {"EN": "Turkey",           "FR": "Turquie",            "ES": "Turquía"},
    "United Kingdom":  {"EN": "United Kingdom",   "FR": "Royaume-Uni",        "ES": "Reino Unido"},
}


def translate_country(name: str, lang: str) -> str:
    """Return the translated country name, falling back to the original if unknown."""
    entry = COUNTRY_TRANSLATIONS.get(name)
    return entry[lang] if entry and lang in entry else name


MONTH_MAP = {
    "january": "01", "february": "02", "march": "03", "april": "04",
    "may": "05",     "june": "06",     "july": "07",  "august": "08",
    "september": "09", "october": "10", "november": "11", "december": "12",
}

# ── Language strings ──────────────────────────────────────────────────────────
LANG = {
    "EN": {
        "title": "Budget Calculator: Exchange Edition",
        "subtitle": "Track your spending abroad, stay in control.",
        "hero_image": "hero_en.jpg",
        "dashboard_image": "dashboard_en.jpg",
        "hero_tagline": "Exchange Edition · Remastered 2026",
        "landing_title": "Welcome",
        "landing_subtitle": "Your data never leaves your device. Upload a file to continue where you left off, or start from scratch.",
        "upload_section": "Upload your file",
        "upload_label": "Accepted: .json (app export), .csv or .xlsx (see structure below)",
        "fresh_btn": "Start fresh",
        "upload_error": "Could not read that file. Check the format matches the structure shown below.",
        "preview_title": "Expected file structure",
        "preview_caption_simple": "Simple format (exported by this app)",
        "preview_caption_legacy": "Legacy format (statswinter24.csv style, also supported)",
        "setup_header": "Budget Setup",
        "total_budget": "Total Budget",
        "budget_currency": "Budget Currency",
        "display_currency": "Display Currency",
        "rates_note": "Rates: approx. 2024 annual averages",
        "duration": "Exchange Duration (months)",
        "init_btn": "Set Total Budget",
        "add_header": "Add Expense",
        "amount": "Amount",
        "exp_currency": "Expense Currency",
        "description": "Description",
        "category": "Category",
        "add_btn": "Add Expense",
        "clear_btn": "Clear All Expenses",
        "reset_btn": "Reset (New Session)",
        "download_header": "Save your data",
        "download_caption": "Download before closing the tab!",
        "save_btn": "Download budget.json",
        "export_csv": "Export to CSV",
        "overview_header": "Budget Overview",
        "initial": "Total Budget",
        "spent": "Total Spent",
        "remaining": "Remaining",
        "monthly": "Monthly Budget",
        "weekly": "Weekly Budget",
        "expenses_header": "Expense Log",
        "no_expenses": "No expenses recorded yet.",
        "charts_header": "Spending Breakdown",
        "pie_title": "Spending by Category",
        "bar_title": "Spending by Entry",
        "cumulative_title": "Cumulative Spending",
        "cumulative_x": "# Entries",
        "currency_log_header": "Currency Log",
        "currency_log_caption": "All currencies detected in your expenses",
        "col_currency": "Currency",
        "col_transactions": "Transactions",
        "col_total_original": "Total (original)",
        "col_total_converted": "Converted",
        "status_good": "You're doing great! Keep it up.",
        "status_warning": "Careful, you're using up your budget.",
        "status_danger": "Alert! You're almost out of budget.",
        "status_over": "You have exceeded your budget!",
        "budget_used": "Budget used",
        "categories": ["Food", "Transport", "Housing", "Entertainment",
                       "Health", "Shopping", "Bar", "Activity & Museums",
                       "Hotel", "Telephone", "Other"],
        "try_it_title": "Try it out",
        "try_it_body": ("Want to see what this app can do? Download "
                        "<a href='https://github.com/stefhooy/Budget-Calculator-Exchange"
                        "/blob/main/data/statswinter24.csv' target='_blank' style='color:#5dade2;'>"
                        "<strong>statswinter24.csv</strong></a> from the GitHub repo and upload it here. "
                        "It contains real spending data across 5 months and 8 countries "
                        "with multiple currencies (HUF, EUR, CAD, SEK, TRY)."),
        "bar_country_title": "Spending by Country",
        "map_title": "Geographic Spending Map",
        "monthly_chart_title": "Monthly Spending vs Budget",
        "monthly_x": "Month",
        "monthly_budget_line": "Monthly Budget",
        "country_drill_header": "Country Deep Dive",
        "select_country": "Select a country to explore",
        "all_label": "All countries",
        "drill_total": "Total spent",
        "drill_pie_title": "Categories in",
        "drill_timeline_title": "Monthly spending in",
        "setup_loaded_msg": "expenses loaded from file. Now set your total budget to continue.",
        "setup_go_btn": "Let's go",
    },
    "FR": {
        "title": "Calculateur de Budget: Échange",
        "subtitle": "Suivez vos dépenses à l'étranger, gardez le contrôle.",
        "hero_image": "hero_fr.jpg",
        "dashboard_image": "dashboard_fr.jpg",
        "hero_tagline": "Édition Échange · Remasterisé 2026",
        "landing_title": "Bienvenue",
        "landing_subtitle": "Vos données ne quittent jamais votre appareil. Importez un fichier pour continuer ou commencez à nouveau.",
        "upload_section": "Importer votre fichier",
        "upload_label": "Acceptés : .json, .csv ou .xlsx (voir structure ci-dessous)",
        "fresh_btn": "Nouveau départ",
        "upload_error": "Impossible de lire ce fichier. Vérifiez que la structure correspond.",
        "preview_title": "Structure attendue du fichier",
        "preview_caption_simple": "Format simple (exporté par cette app)",
        "preview_caption_legacy": "Format legacy (style statswinter24.csv, également supporté)",
        "setup_header": "Configuration du Budget",
        "total_budget": "Budget Total",
        "budget_currency": "Devise du Budget",
        "display_currency": "Devise d'Affichage",
        "rates_note": "Taux : moyennes annuelles approx. 2024",
        "duration": "Durée de l'échange (mois)",
        "init_btn": "Définir le Budget Total",
        "add_header": "Ajouter une Dépense",
        "amount": "Montant",
        "exp_currency": "Devise de la Dépense",
        "description": "Description",
        "category": "Catégorie",
        "add_btn": "Ajouter la Dépense",
        "clear_btn": "Effacer Toutes les Dépenses",
        "reset_btn": "Réinitialiser (Nouvelle Session)",
        "download_header": "Sauvegarder vos données",
        "download_caption": "Téléchargez avant de fermer l'onglet !",
        "save_btn": "Télécharger budget.json",
        "export_csv": "Exporter en CSV",
        "overview_header": "Vue d'Ensemble du Budget",
        "initial": "Budget Total",
        "spent": "Total Dépensé",
        "remaining": "Restant",
        "monthly": "Budget Mensuel",
        "weekly": "Budget Hebdomadaire",
        "expenses_header": "Journal des Dépenses",
        "no_expenses": "Aucune dépense enregistrée.",
        "charts_header": "Répartition des Dépenses",
        "pie_title": "Dépenses par Catégorie",
        "bar_title": "Dépenses par Entrée",
        "cumulative_title": "Dépenses Cumulées",
        "cumulative_x": "Entrées",
        "currency_log_header": "Journal des Devises",
        "currency_log_caption": "Toutes les devises détectées dans vos dépenses",
        "col_currency": "Devise",
        "col_transactions": "Transactions",
        "col_total_original": "Total (original)",
        "col_total_converted": "Converti",
        "status_good": "Vous gérez très bien votre budget !",
        "status_warning": "Attention, vous consommez votre budget.",
        "status_danger": "Alerte ! Vous êtes presque à court de budget.",
        "status_over": "Vous avez dépassé votre budget !",
        "budget_used": "Budget utilisé",
        "categories": ["Nourriture", "Transport", "Logement", "Loisirs",
                       "Santé", "Shopping", "Bar", "Activités & Musées",
                       "Hôtel", "Téléphone", "Autre"],
        "try_it_title": "Essayez !",
        "try_it_body": ("Vous voulez voir ce que cette app peut faire ? Téléchargez "
                        "<a href='https://github.com/stefhooy/Budget-Calculator-Exchange"
                        "/blob/main/data/statswinter24.csv' target='_blank' style='color:#5dade2;'>"
                        "<strong>statswinter24.csv</strong></a> depuis le dépôt GitHub et importez-le ici. "
                        "Il contient des données réelles sur 5 mois et 8 pays "
                        "avec plusieurs devises (HUF, EUR, CAD, SEK, TRY)."),
        "bar_country_title": "Dépenses par Pays",
        "map_title": "Carte Géographique des Dépenses",
        "monthly_chart_title": "Dépenses Mensuelles vs Budget",
        "monthly_x": "Mois",
        "monthly_budget_line": "Budget Mensuel",
        "country_drill_header": "Analyse par Pays",
        "select_country": "Sélectionner un pays",
        "all_label": "Tous les pays",
        "drill_total": "Total dépensé",
        "drill_pie_title": "Catégories en",
        "drill_timeline_title": "Dépenses mensuelles en",
        "setup_loaded_msg": "dépenses chargées. Définissez votre budget total pour continuer.",
        "setup_go_btn": "C'est parti",
    },
    "ES": {
        "title": "Calculadora de Presupuesto: Intercambio",
        "subtitle": "Controla tus gastos en el extranjero, mantén el control.",
        "hero_image": "hero_es.jpg",
        "dashboard_image": "dashboard_es.jpg",
        "hero_tagline": "Edición Intercambio · Remasterizado 2026",
        "landing_title": "Bienvenido",
        "landing_subtitle": "Tus datos nunca salen de tu dispositivo. Sube un archivo para continuar o empieza desde cero.",
        "upload_section": "Subir tu archivo",
        "upload_label": "Formatos: .json, .csv o .xlsx (ver estructura abajo)",
        "fresh_btn": "Empezar de cero",
        "upload_error": "No se pudo leer el archivo. Comprueba que la estructura coincide.",
        "preview_title": "Estructura esperada del archivo",
        "preview_caption_simple": "Formato simple (exportado por esta app)",
        "preview_caption_legacy": "Formato legacy (estilo statswinter24.csv, también soportado)",
        "setup_header": "Configuración del Presupuesto",
        "total_budget": "Presupuesto Total",
        "budget_currency": "Moneda del Presupuesto",
        "display_currency": "Moneda de Visualización",
        "rates_note": "Tasas: medias anuales aprox. 2024",
        "duration": "Duración del intercambio (meses)",
        "init_btn": "Establecer Presupuesto Total",
        "add_header": "Añadir Gasto",
        "amount": "Cantidad",
        "exp_currency": "Moneda del Gasto",
        "description": "Descripción",
        "category": "Categoría",
        "add_btn": "Añadir Gasto",
        "clear_btn": "Borrar Todos los Gastos",
        "reset_btn": "Reiniciar (Nueva Sesión)",
        "download_header": "Guardar tus datos",
        "download_caption": "¡Descarga antes de cerrar la pestaña!",
        "save_btn": "Descargar budget.json",
        "export_csv": "Exportar a CSV",
        "overview_header": "Resumen del Presupuesto",
        "initial": "Presupuesto Total",
        "spent": "Total Gastado",
        "remaining": "Restante",
        "monthly": "Presupuesto Mensual",
        "weekly": "Presupuesto Semanal",
        "expenses_header": "Registro de Gastos",
        "no_expenses": "Ningún gasto registrado todavía.",
        "charts_header": "Desglose de Gastos",
        "pie_title": "Gastos por Categoría",
        "bar_title": "Gastos por Entrada",
        "cumulative_title": "Gastos Acumulados",
        "cumulative_x": "Entradas",
        "currency_log_header": "Registro de Monedas",
        "currency_log_caption": "Todas las monedas detectadas en tus gastos",
        "col_currency": "Moneda",
        "col_transactions": "Transacciones",
        "col_total_original": "Total (original)",
        "col_total_converted": "Convertido",
        "status_good": "¡Lo estás haciendo genial! Sigue así.",
        "status_warning": "Cuidado, estás agotando tu presupuesto.",
        "status_danger": "¡Alerta! Estás casi sin presupuesto.",
        "status_over": "¡Has superado tu presupuesto!",
        "budget_used": "Presupuesto usado",
        "categories": ["Comida", "Transporte", "Alojamiento", "Ocio",
                       "Salud", "Compras", "Bar", "Actividades & Museos",
                       "Hotel", "Teléfono", "Otro"],
        "try_it_title": "Pruébalo",
        "try_it_body": ("¿Quieres ver lo que puede hacer esta app? Descarga "
                        "<a href='https://github.com/stefhooy/Budget-Calculator-Exchange"
                        "/blob/main/data/statswinter24.csv' target='_blank' style='color:#5dade2;'>"
                        "<strong>statswinter24.csv</strong></a> del repositorio de GitHub y súbelo aquí. "
                        "Contiene datos reales de gastos durante 5 meses y 8 países "
                        "con múltiples divisas (HUF, EUR, CAD, SEK, TRY)."),
        "bar_country_title": "Gastos por País",
        "map_title": "Mapa Geográfico de Gastos",
        "monthly_chart_title": "Gastos Mensuales vs Presupuesto",
        "monthly_x": "Mes",
        "monthly_budget_line": "Presupuesto Mensual",
        "country_drill_header": "Análisis por País",
        "select_country": "Seleccionar un país",
        "all_label": "Todos los países",
        "drill_total": "Total gastado",
        "drill_pie_title": "Categorías en",
        "drill_timeline_title": "Gastos mensuales en",
        "setup_loaded_msg": "gastos cargados. Establece tu presupuesto total para continuar.",
        "setup_go_btn": "¡Vamos!",
    },
}
